export type Guide = { slug: string; title: string; description: string; category: string; readTime: string; published: string; intro: string; sections: { heading: string; paragraphs: string[]; list?: string[] }[] };

const coreGuides: Guide[] = [
  {slug:"why-websites-require-specific-image-sizes",title:"Why websites require specific image sizes",description:"Understand file-size and pixel limits, why upload forms enforce them, and how to prepare an image that passes both checks.",category:"File size basics",readTime:"6 min read",published:"2026-08-10",intro:"An upload message such as “maximum 200KB” can feel arbitrary, especially when a phone has just created a perfectly good 6MB photograph. The limit usually exists because the receiving system has to store, transmit, inspect and display thousands—or millions—of other files too.",sections:[{heading:"File size and dimensions solve different problems",paragraphs:["File size describes storage weight: the number of bytes transferred and kept. Pixel dimensions describe the grid that forms the picture. A 1,200 × 800 image can be either 90KB or 900KB depending on its format, detail and encoding settings.","A portal may validate both. Resizing handles the pixel rule; compression handles the KB or MB rule. Doing them in that order generally gives you more control over the final appearance."]},{heading:"The reasons behind a limit",paragraphs:["Smaller files make pages load faster, reduce mobile-data use and lower the time an upload can fail. Fixed dimensions also keep profile cards, ID layouts and automated review screens consistent.","For an organization, modest limits can reduce storage costs and make backups, moderation and document retrieval more predictable. The restriction is rarely a judgment about your photo; it is an engineering budget."],list:["Performance on slow or unstable networks","Consistent layouts and previews","Storage and backup efficiency","Compatibility with older processing systems"]},{heading:"How to pass an upload check cleanly",paragraphs:["Read the complete instruction, including format, dimensions, aspect ratio, minimum size and maximum size. Crop first, resize next and compress last. Then open the downloaded result and confirm its properties before submitting.","Avoid repeatedly saving the same JPEG. Each lossy generation can add artifacts. Keep one untouched source and create new delivery copies from it for every different requirement."]}]},
  {slug:"jpeg-vs-png-which-compresses-better",title:"JPEG vs PNG: which compresses better?",description:"A practical comparison of JPG and PNG compression for photos, screenshots, graphics, transparency and strict upload limits.",category:"Format guide",readTime:"7 min read",published:"2026-08-12",intro:"JPEG and PNG are both familiar image formats, but they make very different promises. JPEG is willing to simplify visual information to save space. PNG preserves pixel values exactly. The better choice depends on what the image contains and what the destination accepts.",sections:[{heading:"JPEG is usually lighter for photographs",paragraphs:["Photos contain thousands of subtle color changes. JPEG groups and approximates some of that detail in ways designed to be less noticeable to human vision. With a sensible quality setting, the savings can be large while the image still looks natural at its intended size.","Push JPEG too far and you will see block shapes, halos around edges and smeared texture. Starting from a large, clean source gives the encoder more room to make a good compromise."]},{heading:"PNG protects crisp edges",paragraphs:["PNG uses lossless compression. It excels at screenshots, interface elements, flat illustrations, diagrams and text because every decoded pixel matches the encoded pixel. It can also store transparency.","A photographic PNG is often much heavier than a comparable JPEG. Converting a JPEG photo to PNG does not recover details the JPEG already discarded; it commonly creates a larger file with the same visible limitations."]},{heading:"Choose based on the image—not habit",paragraphs:["Use JPEG for ordinary photos when compatibility and small size matter. Use PNG for sharp graphics, transparent assets and images that will be edited repeatedly. WebP is another useful option when the destination supports it because it handles both photographs and transparency efficiently."],list:["Portrait or landscape photo: start with JPEG or WebP","Logo with transparent background: choose PNG or WebP","Screenshot with small text: choose PNG","Strict legacy form: follow its listed format exactly"]}]},
  {slug:"reduce-photo-size-for-job-applications",title:"How to reduce photo size for job applications",description:"Prepare a clear application photo that meets format, pixel and KB limits without repeated failed uploads.",category:"Step by step",readTime:"6 min read",published:"2026-08-15",intro:"A recruitment form can reject an otherwise suitable portrait because one technical detail is wrong. The calmest approach is to separate the requirements, prepare a clean source once and then make a dedicated copy for that application.",sections:[{heading:"Write down every requirement",paragraphs:["Look beside the upload field and in the application instructions. Record the accepted format, maximum and minimum file size, pixel dimensions or aspect ratio, background guidance and any naming rule. Do not assume that a file below the KB limit automatically qualifies.","Requirements can change between recruitment cycles. Use the current official notice rather than a remembered value or an unofficial example."]},{heading:"Start with a strong portrait",paragraphs:["Use even front lighting, a simple background and a sharp image. Frame the head and shoulders with the subject facing the camera. Avoid photographing a printed photo if the original digital version is available; paper texture and glare make compression less efficient.","Crop away unrelated space. Every unnecessary pixel competes with important facial detail when you later target a very small file size."]},{heading:"Resize, compress and verify",paragraphs:["First resize to the required pixel dimensions or ratio. Then choose the relevant PixSqueeze target—such as 20KB or 50KB—and compress the prepared copy. Check the downloaded extension and actual byte size in your file information.","Preview the final file at normal scale. Keep the untouched original and the finished application copy in clearly named locations so you do not accidentally upload the wrong one."],list:["Confirm the latest official rule","Crop and resize before compression","Target slightly below a strict maximum","Open and inspect the downloaded copy"]}]},
  {slug:"how-image-compression-affects-quality",title:"How image compression affects quality",description:"Learn what changes during image compression and how to keep the details that matter while meeting a smaller file-size target.",category:"Compression guide",readTime:"7 min read",published:"2026-08-18",intro:"Compression is not one magic slider. An image’s file weight depends on its dimensions, format, visual complexity, metadata and encoding quality. Understanding those levers makes it much easier to choose an acceptable result instead of chasing a number blindly.",sections:[{heading:"Lossless and lossy compression",paragraphs:["Lossless methods reorganize data so the decoded pixels remain identical. PNG uses this approach. Lossy methods allow carefully chosen differences to achieve much smaller files; JPEG and common WebP settings work this way.","Lossy does not automatically mean poor. At moderate settings, a result can look extremely close to the source during normal viewing. Problems appear when the file budget is too small for the image dimensions and complexity."]},{heading:"Why some images shrink more easily",paragraphs:["Smooth backgrounds, gentle gradients and large areas of similar color are efficient to describe. Fine hair, grass, confetti, fabric patterns, low-light noise and tiny text are harder. That is why two photos from the same phone can produce different output sizes at one quality setting.","Cropping out a busy background can improve both composition and compression. Resizing an oversized source is another powerful lever because fewer pixels need to be stored."]},{heading:"Protect the details that matter",paragraphs:["Evaluate the result at the size where people will use it. A profile photo does not need poster-level texture, but eyes and facial boundaries should remain clear. A scan containing legal text needs a different quality threshold from a decorative thumbnail.","Keep the source. Compression should create a delivery copy, never your only copy. If a future use needs more resolution, you can return to the original rather than enlarging an already reduced file."]}]}
];

const additionalGuides: Guide[] = [
  {
    slug: "compress-images-without-losing-quality",
    title: "Compress images without losing quality",
    description: "Learn how to reduce image file size while protecting visible detail, choosing the right format and avoiding repeated compression damage.",
    category: "Compression guide",
    readTime: "7 min read",
    published: "2026-08-20",
    intro: "“Without losing quality” usually means without a visible loss at the size where the image will be used. Every image has a different file-size floor, but a careful workflow can remove substantial weight while keeping the details people actually notice.",
    sections: [
      { heading: "Start with dimensions, not only quality", paragraphs: ["A camera photo can be thousands of pixels wider than a website, profile card or application preview needs. Resizing excessive dimensions often saves more data cleanly than forcing a full-resolution image through very low encoding quality.", "Match the pixel dimensions to the largest real display size. Keep a separate original for print, editing or future uses that need more resolution."] },
      { heading: "Choose a format that fits the content", paragraphs: ["JPG is usually efficient for photographs. PNG protects crisp text, flat graphics and transparency. WebP can handle both photos and transparency with efficient modern compression.", "Changing a photo from JPG to PNG does not restore lost detail and normally makes it larger. Choose the format based on the pixels and the destination’s compatibility rules."], list: ["Photos: JPG or WebP", "Screenshots and diagrams: PNG", "Transparent web graphics: PNG or WebP", "Strict forms: use the exact requested format"] },
      { heading: "Avoid generation loss", paragraphs: ["Every lossy save starts from the pixels in the current file. Compressing an already compressed copy again can amplify blocks, ringing and smeared texture.", "Keep one clean source and create each smaller version directly from it. Inspect the result at normal viewing size before deciding whether the saving is worth the visual change."] },
    ],
  },
  {
    slug: "best-image-size-for-websites",
    title: "Best image size for faster websites",
    description: "Choose practical pixel dimensions, formats and file-size budgets for website images without making them look unnecessarily soft.",
    category: "Web performance",
    readTime: "8 min read",
    published: "2026-08-21",
    intro: "There is no single perfect KB number for every website image. A small card thumbnail and a full-width hero solve different jobs. The useful goal is to deliver no more pixels or bytes than the layout needs while preserving the visual quality appropriate to that placement.",
    sections: [
      { heading: "Match the source to the rendered width", paragraphs: ["If a content column never displays an image wider than 800 pixels, sending a 4,000-pixel phone photo wastes transfer time and decoding memory. Export near the largest rendered width, with a higher-density version when the design needs it.", "Responsive image markup can give browsers several candidates so a phone does not download the same file as a large desktop display."] },
      { heading: "Use a budget as a starting point", paragraphs: ["Simple thumbnails can often stay well below 100KB, while detailed article images may need more. A prominent hero deserves a larger allowance than a small decorative card, but it should still be tested on a mobile connection.", "Treat the budget as a diagnostic boundary, not a guarantee of quality. Image complexity, dimensions and format determine how far a file can shrink."], list: ["Crop unused content", "Resize to real layout dimensions", "Use JPG or WebP for photos", "Keep text-heavy graphics readable", "Test the actual page on mobile"] },
      { heading: "Protect the largest visible image", paragraphs: ["The largest image near the top of a page often has an outsized effect on perceived speed. Give it explicit dimensions, avoid lazy-loading it when it is immediately visible, and make its file as light as the design permits.", "Compression tools prepare the asset, but correct HTML sizing, caching and delivery remain part of the website implementation."] },
    ],
  },
  {
    slug: "reduce-image-size-for-email-and-messaging",
    title: "Reduce image size for email and messaging",
    description: "Make photos smaller for email attachments and messaging while keeping a clear copy and choosing compatible dimensions and formats.",
    category: "Step by step",
    readTime: "6 min read",
    published: "2026-08-23",
    intro: "Large phone photos can make messages slow to send, consume mobile data and exceed an attachment limit. A dedicated sharing copy is usually better than repeatedly retrying the original or relying on an app’s unpredictable automatic compression.",
    sections: [
      { heading: "Decide how the image will be used", paragraphs: ["A photo meant only for screen viewing does not need the same dimensions as a file intended for printing or detailed editing. Keep the original and make a smaller delivery copy for the message.", "For ordinary viewing, reducing a very large camera photo to a sensible screen resolution can cut far more weight than a small quality adjustment alone."] },
      { heading: "Pick a compatible file", paragraphs: ["JPG is the safest choice for normal photographs because it is widely accepted and efficient. WebP may be smaller, but the recipient’s older software might not recognize it. PNG is useful for screenshots and graphics with crisp text.", "HEIC photos from an iPhone may need a JPG copy for recipients using older devices or document systems."] },
      { heading: "Compress, inspect and attach", paragraphs: ["Set a target comfortably below the service’s attachment ceiling, compress the source once and open the finished copy. Check faces, text and other important details at normal size.", "Attach the new file and retain the source separately. If several images are needed, compress them as a batch so the whole message remains manageable."], list: ["Keep the original", "Resize excessive dimensions", "Use JPG for broad compatibility", "Leave room below the attachment limit", "Preview before sending"] },
    ],
  },
  {
    slug: "convert-heic-photos-to-jpg",
    title: "How to convert HEIC photos to JPG",
    description: "Convert iPhone HEIC and HEIF photos to compatible JPG files, understand quality choices and prepare smaller copies for uploads.",
    category: "Format guide",
    readTime: "6 min read",
    published: "2026-08-24",
    intro: "HEIC stores modern phone photos efficiently, but many upload portals, editors and older devices still expect JPG. Converting a separate copy solves compatibility without deleting or changing the efficient original on your phone.",
    sections: [
      { heading: "Why an upload may reject HEIC", paragraphs: ["A file can be a valid photo and still fail when the receiving system checks only a short list of extensions or decoders. JPG remains the most broadly recognized photographic format across browsers, office tools, forms and email clients.", "Check whether the destination also gives a maximum file size or pixel dimension. Conversion alone may not satisfy those separate rules."] },
      { heading: "Convert locally for privacy", paragraphs: ["A browser-based converter can decode the HEIC file on your device and create a JPG copy without uploading the personal photo to a processing server.", "JPG has no transparency and uses lossy encoding. For normal phone photographs that tradeoff is usually appropriate, but keep the HEIC source for editing and archival use."] },
      { heading: "Prepare the final upload copy", paragraphs: ["Choose the HEIC photo, convert it to JPG, then inspect orientation and detail. If the destination specifies a KB or MB ceiling, compress the new copy to that limit and verify its properties before submission.", "Use clear filenames and retain both versions until the portal or recipient confirms acceptance."], list: ["Keep the source HEIC", "Choose JPG for maximum compatibility", "Check orientation after conversion", "Meet file-size and dimension rules separately"] },
    ],
  },
];

export const guides: Guide[] = [...coreGuides, ...additionalGuides];

export const getGuide = (slug:string) => guides.find((guide) => guide.slug === slug);
