export type SizePage = {
  slug: string;
  label: string;
  kb: number;
  title: string;
  description: string;
  intro: string;
  common: string;
  strategy: string;
  check: string;
  faqs: { question: string; answer: string }[];
};

export const targetSizeFaqs = [
  {
    question: "Does compressing reduce image quality?",
    answer: "Compression can reduce visible quality when the target is much smaller than the source. PixSqueeze searches for the highest practical quality below your limit and reduces pixel dimensions only when needed.",
  },
  {
    question: "Is this tool free and unlimited?",
    answer: "Yes. PixSqueeze is free and has no account, watermark or daily server quota. Practical batch limits depend on your browser and available device memory because processing happens locally.",
  },
  {
    question: "Do I need to create an account?",
    answer: "No. You can add, compress and download images without signing up or providing personal details.",
  },
  {
    question: "Which image formats are supported?",
    answer: "PixSqueeze accepts JPG and JPEG, PNG, WebP, HEIC and HEIF images. Compressed results can be downloaded as JPG, PNG or WebP.",
  },
  {
    question: "Are my images uploaded to a server?",
    answer: "No. Your images are decoded and compressed on your device using browser APIs. PixSqueeze has no image-upload server and cannot view or store the files you select.",
  },
] as const;

const baseSizePages: SizePage[] = [
  { slug:"5kb",label:"5KB",kb:5,title:"Compress Image to 5KB Online Free — Tiny & Precise",description:"Compress an image to 5KB online for free. Create an ultra-small photo in your browser with no upload, account or watermark.",intro:"A 5KB image is exceptionally compact. It is most useful when an older form, lightweight directory, thumbnail slot or low-bandwidth system sets a very strict upload ceiling. PixSqueeze gradually adjusts image quality and pixel dimensions to find a result below that limit while keeping the subject recognizable.",common:"At this size, a full-resolution photograph cannot retain fine texture. Simple headshots, signatures, icons and graphics with uncluttered backgrounds respond best. Crop away empty space before compressing and start with an image whose subject already fills the frame.",strategy:"Expect visible simplification at 5KB. The compressor may reduce dimensions as well as encoding quality because lowering quality alone is rarely enough. For a document photo, check that facial features and edges remain legible at the size the receiving portal displays.",check:"After downloading, confirm the file is 5KB or less in your device’s file details, then preview it once more before submitting. Different operating systems round displayed sizes differently, so PixSqueeze targets bytes rather than a rounded label.",faqs:[{question:"Can a photo really be compressed to 5KB?",answer:"Yes, although the image will need small pixel dimensions and strong compression. A tightly cropped, simple photo gives the clearest result."},{question:"Will my original image be changed?",answer:"No. PixSqueeze creates a new downloadable file and leaves the original untouched on your device."},{question:"Why is my result smaller than exactly 5KB?",answer:"The tool stays under the limit. Image encoders produce discrete file sizes, so the nearest safe result may be slightly below 5KB."}]},
  { slug:"10kb",label:"10KB",kb:10,title:"Compress Image to 10KB Online — Free Photo Reducer",description:"Reduce image size to 10KB online with a private browser-based compressor. Fast, free and designed for strict photo upload limits.",intro:"A 10KB limit often appears in compact profile systems, signature uploads and legacy application forms. It leaves a little more room than 5KB, but successful results still depend on a clear crop and modest pixel dimensions. This page begins with 10KB already selected so you can move directly from choosing a file to downloading it.",common:"Scanned signatures, small ID portraits and simple supporting graphics are good candidates. If a portal gives both a pixel specification and a file-size ceiling, resize to the required dimensions first, then use this compressor for the final file-weight adjustment.",strategy:"PixSqueeze tries several encoding-quality levels and reduces dimensions only when needed. A plain background and even lighting compress more efficiently than noisy shadows, patterned walls or a photo of a printed photo.",check:"Open the result at its intended display size, not only zoomed in. A 10KB portrait can look rough at full-screen magnification yet remain perfectly serviceable inside a small application preview. Always keep the original in case the portal later requests a larger copy.",faqs:[{question:"How do I reduce a JPG to 10KB?",answer:"Add the JPG, keep the target at 10KB, choose Compress images, and download the new file after processing."},{question:"Does 10KB mean 10,000 bytes?",answer:"Most upload tools use binary kilobytes. PixSqueeze treats 10KB as 10 × 1,024 bytes and aims at or below that amount."},{question:"Are 10KB photos uploaded to PixSqueeze?",answer:"No. Processing happens inside your browser; your selected images are not transferred to our server."}]},
  { slug:"20kb",label:"20KB",kb:20,title:"Compress Image to 20KB Online Free — Quick & Private",description:"Compress a JPG, PNG, WebP or HEIC image to 20KB online. No server upload, signup or watermark—just a fast 20KB photo reducer.",intro:"Twenty kilobytes is a common low-end target for profile pictures, scanned signatures and small application photographs. It can preserve a recognizable portrait when the image is tightly framed, making it a practical compromise between a demanding upload rule and readable visual detail.",common:"Forms for exams, permits and recruitment may specify a range rather than an exact value—for example, 10KB to 20KB. This tool aims below 20KB. If the portal also has a minimum, inspect the downloaded size and use a slightly higher target if necessary.",strategy:"The compressor tests the image at multiple quality settings, keeping the largest valid candidate under your target. If quality changes are insufficient, it carefully scales the image down. Starting from a clean digital image generally produces a better 20KB file than compressing a screenshot or a previously compressed social-media copy.",check:"Check three things before upload: the file size, the accepted format and any pixel-dimension rule. They are separate requirements. A file can be under 20KB and still be rejected for having the wrong dimensions or extension.",faqs:[{question:"Is this 20KB compressor free?",answer:"Yes. There is no sign-up, watermark or usage charge for processing images in your browser."},{question:"Can I compress a PNG to 20KB?",answer:"Yes. For strong reductions, a PNG may be encoded as WebP to preserve transparency more efficiently."},{question:"Can I process several 20KB photos?",answer:"Yes. Add multiple images, run one batch, then download each finished result."}]},
  { slug:"30kb",label:"30KB",kb:30,title:"Compress Image to 30KB Online Free — Accurate Reducer",description:"Reduce an image to 30KB online for free. Private batch compression for JPG, PNG, WebP and HEIC files, entirely in your browser.",intro:"A 30KB image is small enough for restrictive online forms while allowing more facial and edge detail than ultra-low targets. It is a frequent choice for candidate photos, small identity images, signatures and lightweight directory thumbnails.",common:"For portraits, crop around the head and shoulders before reducing the file. Unused wall or scenery consumes pixels that could otherwise describe the face. For signatures, a high-contrast dark mark on a clean pale background usually stays clearer at 30KB than a dim phone photo.",strategy:"PixSqueeze begins by changing encoding quality, then adjusts resolution only when necessary. This preserves useful dimensions whenever the source permits. Results vary because a detailed outdoor photograph contains more visual information than a studio portrait against one color.",check:"Use the downloaded copy for the form and retain your source separately. If a site reports that the file is too large despite showing 30KB in your file manager, lower the target to 29KB to leave room for different rounding conventions.",faqs:[{question:"How close will the output be to 30KB?",answer:"The compressor seeks the closest safe encoding below the target. The final size can be lower when the encoder cannot produce an in-between result."},{question:"Does compression remove photo metadata?",answer:"Canvas-based output normally leaves camera metadata behind, which saves space and reduces unnecessary embedded information."},{question:"Which format is best for a 30KB portrait?",answer:"JPG or WebP usually handles photographic detail more efficiently than PNG at this small size."}]},
  { slug:"50kb",label:"50KB",kb:50,title:"Compress Image to 50KB Online Free — Fast & Accurate",description:"Compress image to 50KB online free. Make job application, exam and document photos smaller with private in-browser processing.",intro:"A 50KB photo is widely useful for online applications, profile forms and document portals that need a clear preview without a heavy upload. It usually gives a well-cropped headshot enough room for recognizable features while remaining quick to transfer on slower connections.",common:"Government, recruitment and education portals often combine a maximum file size with exact dimensions or an aspect ratio. Treat each rule separately: prepare the framing first, use the requested dimensions if stated, and then compress the finished image to 50KB.",strategy:"This reducer searches across encoding quality and, only when necessary, image dimensions. A sharp source with soft, even lighting compresses cleanly. Heavy grain, text overlays and busy backgrounds make the encoder spend more bytes, so simple preparation can improve the final appearance.",check:"Review the result at 100% and verify that the eyes, outline and any required text remain clear. Then check the actual file properties. PixSqueeze aims below the 50KB ceiling rather than risking a result that a strict portal reads as a few bytes too large.",faqs:[{question:"How can I compress an image to 50KB for an application?",answer:"Select the prepared photo, leave 50KB in the target field, run compression, inspect the preview and download the result."},{question:"Will a 50KB photo still look clear?",answer:"Usually, especially for a tightly cropped portrait. Very large or highly detailed scenes may require smaller dimensions to meet the limit."},{question:"Can I use PixSqueeze on a phone?",answer:"Yes. The upload, compression and download flow works in modern mobile browsers as well as desktop browsers."},{question:"Is the output guaranteed below 50KB?",answer:"The compressor selects a candidate at or below the byte limit. Always confirm the portal’s separate format and dimension rules."}]},
  { slug:"100kb",label:"100KB",kb:100,title:"Compress Image to 100KB Online — Free & Secure",description:"Reduce image size to 100KB online with a free, private photo compressor. Batch-process JPG, PNG, WebP and HEIC in your browser.",intro:"One hundred kilobytes is a versatile target for web forms, profile photographs and content-management uploads. It is small enough to load quickly but roomy enough for a polished headshot, product thumbnail or medium-size supporting image.",common:"A 100KB ceiling is often used to keep form submissions responsive on mobile networks. It can also help teams standardize profile images so lists and directories do not become unnecessarily heavy. You can add several files here when the same limit applies to a whole set.",strategy:"The tool attempts to preserve resolution by exploring efficient quality levels first. If the source still exceeds 100KB, it scales the dimensions gradually. Modern WebP sources may need less reduction than JPEGs, while photographic PNGs often need a format or dimension change to become meaningfully smaller.",check:"Compare the before and after figures displayed beside each preview. Compression is most valuable when it removes substantial weight without harming the intended viewing size. If your original is already below 100KB, PixSqueeze returns it without needless re-encoding.",faqs:[{question:"Can I make an image exactly 100KB?",answer:"PixSqueeze targets the closest practical result at or below 100KB. Exact byte counts are not always possible with browser encoders."},{question:"What happens if my image is already under 100KB?",answer:"The original file is used as the result so it does not lose quality from unnecessary compression."},{question:"Can I reduce HEIC to 100KB?",answer:"Yes. HEIC files are decoded locally in compatible browsers and exported to a broadly supported compressed format."}]},
  { slug:"150kb",label:"150KB",kb:150,title:"Compress Image to 150KB Online — Clear, Fast, Free",description:"Compress photos to 150KB online without uploading them. A free target-size reducer for forms, websites and profile images.",intro:"A 150KB image works well when clarity matters but an upload form still imposes a modest ceiling. It can accommodate medium-resolution portraits, small product pictures and editorial thumbnails with noticeably more texture than very low KB targets.",common:"Use 150KB when a portal states that value as its maximum or when you want a consistent lightweight image set for a website. Because the target allows reasonable visual detail, start with a properly cropped image rather than shrinking it aggressively in advance.",strategy:"PixSqueeze chooses the largest safe result it can find beneath your limit. The exact balance depends on the source: smooth skies and plain walls compress readily, while hair, foliage, fabric patterns and sensor noise need more data. The tool responds to that complexity automatically.",check:"After export, inspect thin lines and small text if those details matter. A standard photograph should remain comfortable to view, but scans containing fine print may be better saved as a PDF or given a larger file allowance.",faqs:[{question:"Is 150KB enough for a profile photo?",answer:"For most small and medium profile displays, yes. Good lighting and a close crop help preserve a clean result."},{question:"Can I compress multiple photos to 150KB?",answer:"Yes. Batch upload is supported, and every image is processed locally one after another."},{question:"Does PixSqueeze add a watermark?",answer:"No. Your downloaded image contains no PixSqueeze branding or watermark."}]},
  { slug:"200kb",label:"200KB",kb:200,title:"Compress Image to 200KB Online Free — Quality First",description:"Reduce image size to 200KB online for website uploads and forms. Free, private compression with live before-and-after results.",intro:"Two hundred kilobytes is a popular ceiling for website uploads because it offers a strong balance: enough data for a useful content image, yet light enough to avoid burdening a page or form. It is also common for application photographs and scanned supporting documents.",common:"For web publishing, 200KB is a sensible budget for thumbnails and modest content images, though the right limit always depends on displayed dimensions. There is little benefit in keeping a 4,000-pixel source if a page only shows it at 800 pixels wide.",strategy:"The compressor first reduces encoding overhead and then scales pixels only if the target still cannot be reached. You can process JPG, PNG, WebP and HEIC sources. Files with transparency may be exported as WebP when that provides a better small result.",check:"Preview the output where it will actually be used. A website image should be assessed at its rendered size and on a representative screen. For formal submissions, confirm that the receiving portal accepts the downloaded extension as well as the 200KB file weight.",faqs:[{question:"How do I reduce a photo below 200KB?",answer:"Choose the photo, keep the prefilled 200KB target, select Compress images, and download the completed version."},{question:"Will 200KB be good quality?",answer:"It is usually enough for a clear medium-size web image. Output quality depends on dimensions and the amount of fine detail in the source."},{question:"Is there a daily limit?",answer:"No. Since processing uses your own browser, PixSqueeze does not impose a server queue or daily file limit."}]},
  { slug:"300kb",label:"300KB",kb:300,title:"Compress Image to 300KB Online — Private Photo Tool",description:"Compress an image to 300KB online free. Keep more detail while meeting upload limits with local, browser-only processing.",intro:"A 300KB target preserves generous detail for most online uses while still cutting down oversized camera images. It suits portfolio previews, article graphics, real-estate thumbnails and forms that allow a little more room for legibility.",common:"This limit is especially useful when the image contains texture or readable visual information that suffered at smaller targets. It can also standardize a mixed batch of phone photos before they enter a content system, helping pages stay predictable without making every image look heavily compressed.",strategy:"Complexity—not just dimensions—controls file weight. Two images with identical pixel measurements can differ greatly when one has a smooth background and the other contains leaves, crowds or grain. PixSqueeze evaluates each file individually rather than applying one fixed quality number to the entire batch.",check:"Use the displayed reduction percentage as context, not as a quality score. A 90% saving can be excellent when the source was needlessly large, while a 10% saving may be all an already optimized image can offer. Judge the preview and required limit together.",faqs:[{question:"Can I batch-compress images to 300KB?",answer:"Yes. Select several files and the tool will target 300KB for each one."},{question:"Does a smaller file change pixel dimensions?",answer:"Sometimes. PixSqueeze preserves dimensions when quality adjustment is enough and scales down only when the target requires it."},{question:"Where are my images stored?",answer:"They are not stored by PixSqueeze. The browser processes them locally, and closing the page clears the working session."}]},
  { slug:"500kb",label:"500KB",kb:500,title:"Compress Image to 500KB Online Free — Keep It Sharp",description:"Reduce photos to 500KB online with private browser compression. Ideal for clearer website images, forms and email attachments.",intro:"Five hundred kilobytes gives most photographs ample room to remain crisp at typical website and document-preview sizes. It is a useful ceiling for email attachments, property images, portfolio previews and portals that accept larger supporting pictures.",common:"Large modern phone photos often weigh several megabytes because they contain far more pixels than a browser or form needs. Bringing them down to 500KB can make transfers noticeably faster while retaining a comfortable viewing experience on laptops and phones.",strategy:"At this target, PixSqueeze can often keep substantial pixel dimensions and rely primarily on efficient re-encoding. The result depends on the source format and detail. A previously optimized WebP may change little, while a camera JPEG with metadata and high resolution can shrink dramatically.",check:"If the destination specifies only a maximum, a result below 500KB is valid. If it also calls for print-quality reproduction, verify its resolution requirement before compressing; file weight alone does not describe print detail.",faqs:[{question:"Is 500KB smaller than 1MB?",answer:"Yes. Using binary units, 1MB equals 1,024KB, so 500KB is a little under half of one megabyte."},{question:"Can I email the compressed result?",answer:"Yes. Download it first, then attach the new file in your email app."},{question:"Will compression overwrite my original?",answer:"No. The browser creates a separate file with “pixsqueeze” in its name."}]},
  { slug:"1mb",label:"1MB",kb:1024,title:"Compress Image to 1MB Online Free — High Quality",description:"Compress an image to 1MB online without uploading it. Free high-quality reduction for large photos, portals and sharing.",intro:"A one-megabyte image is a practical high-quality limit for uploads, email and online portfolios. It usually retains plenty of detail while being far easier to transfer than an untouched multi-megabyte phone or camera file.",common:"Choose 1MB when a service rejects large originals but the image still needs to support a generous on-screen view. It is also useful for preparing a consistent batch before sharing, particularly when recipients may be using limited storage or mobile data.",strategy:"Because the target is roomy, the compressor prioritizes dimensions and applies only as much quality reduction as needed. Images already below 1MB pass through untouched. This avoids the subtle degradation that can accumulate each time a lossy image is re-encoded.",check:"Remember that some portals display MB using decimal units while others use binary units. PixSqueeze treats 1MB as 1,024KB and remains at or below that byte budget. If a particularly strict service disagrees, target 990KB for extra margin.",faqs:[{question:"How many KB are in the 1MB target?",answer:"PixSqueeze uses 1,024KB for one megabyte, matching common binary file-size reporting."},{question:"Can I compress a phone photo to 1MB?",answer:"Yes. Large phone photos are ideal candidates and normally retain strong visual quality at this limit."},{question:"Will files under 1MB be compressed again?",answer:"No. They are returned unchanged because further encoding would add no file-size benefit."}]},
  { slug:"2mb",label:"2MB",kb:2048,title:"Compress Image to Under 2MB Online Free",description:"Make JPG, PNG, WebP or HEIC photos less than 2MB. Free private image compression in your browser with no upload or signup.",intro:"Two megabytes is a generous upload ceiling that can preserve high resolution and fine detail. Many portals use it to prevent unbounded camera files while still accommodating clear documentation, listings, portfolios and application evidence.",common:"Current phones can create images well over 5MB, especially in complex scenes or high-resolution modes. A 2MB copy is often visually close to the original during normal screen viewing but is quicker to attach, upload and archive in a web system.",strategy:"PixSqueeze tests light compression first and only becomes more assertive when the file remains above the limit. For a large source, it may reduce excessive dimensions; for a moderately sized JPEG, a small quality adjustment may be sufficient. Every file is evaluated on its own.",check:"Use 2MB only when it matches the destination’s stated limit or your chosen performance budget. Smaller can be better for a thumbnail, while important zoomable details may deserve the full allowance. Download and inspect the new copy before removing or archiving your original.",faqs:[{question:"Can I reduce a 10MB photo to 2MB?",answer:"Yes. Most large camera images can reach 2MB with a combination of efficient encoding and, where necessary, scaled dimensions."},{question:"Can I make a JPG less than 2MB?",answer:"Yes. Add the JPG, keep the 2MB target selected, compress it and download the result. Use 1.9MB if the destination applies a stricter decimal file-size limit."},{question:"Is 2MB the same as 2MP?",answer:"No. MB measures file weight, while MP measures the number of pixels in the image. PixSqueeze targets file weight."},{question:"Does the tool work offline?",answer:"After the page and any required decoder have loaded, the core canvas processing occurs locally in your browser."},{question:"Can I select HEIC photos from an iPhone?",answer:"Yes. HEIC decoding is loaded when needed, then processing and export remain on your device."}]}
];

const additionalSizePages: SizePage[] = [
  {
    slug: "15kb", label: "15KB", kb: 15, title: "Compress Image to 15KB Online Free",
    description: "Compress an image to 15KB free with private browser processing. JPG, PNG, WebP and HEIC files are never uploaded.",
    intro: "A 15KB ceiling sits between the extremely restrictive 10KB and more forgiving 20KB targets. It is useful for scanned signatures, compact profile pictures and older application portals where every kilobyte matters. PixSqueeze starts with encoding quality and reduces dimensions only when the source cannot otherwise fit.",
    common: "Use 15KB when the destination states it as a maximum or gives a range ending at 15KB. A close crop, plain background and clean source preserve more recognizable detail than a noisy screenshot or repeatedly saved photo.",
    strategy: "For portraits, remove unused background before compression. For signatures, use dark ink on an evenly lit pale background. Those choices let the encoder spend limited bytes on the subject rather than visual noise.",
    check: "Confirm the result is at or below 15KB, then check its extension and pixel dimensions. A valid file size does not override separate format or aspect-ratio rules.",
    faqs: [{ question: "Can a portrait remain clear at 15KB?", answer: "A tightly cropped small portrait can remain recognizable, although fine texture will be reduced at such a strict limit." }],
  },
  {
    slug: "40kb", label: "40KB", kb: 40, title: "Compress Image to 40KB Online Free",
    description: "Compress an image to 40KB free and privately. Reduce JPG, PNG, WebP or HEIC files in your browser with no upload.",
    intro: "Forty kilobytes is a practical target for recruitment forms, exam registrations, profile systems and compact document photos. It gives a well-prepared headshot more room than ultra-small limits while remaining light enough for strict portals and slow connections.",
    common: "A 40KB requirement may appear alongside an exact width, height or aspect ratio. Prepare those dimensions first, then compress the finished copy. Solving the two rules separately produces a more predictable upload file.",
    strategy: "Start from a sharp photo with even light and a simple background. PixSqueeze searches for the strongest encoding below 40KB and scales the image only if quality adjustment is not enough.",
    check: "Open the download at its expected display size and verify faces, signatures or required text remain readable. Keep the original in case a different portal asks for a larger version.",
    faqs: [{ question: "Is 40KB suitable for an application photo?", answer: "It can be, provided the destination accepts the result’s format, dimensions and visual quality. Always follow the current portal instructions." }],
  },
  {
    slug: "60kb", label: "60KB", kb: 60, title: "Compress Image to 60KB Online Free",
    description: "Compress an image to 60KB online free. Private exact-size compression for JPG, PNG, WebP and HEIC with no upload.",
    intro: "A 60KB image can retain a useful amount of portrait and document detail while meeting a modest portal limit. The target is common enough in application workflows to deserve a ready-to-use preset instead of repeated manual quality guesses.",
    common: "Use the 60KB preset for online forms, profile photographs and lightweight content images that explicitly set this maximum. If the destination gives a minimum as well, inspect the result and make sure it falls inside the complete allowed range.",
    strategy: "PixSqueeze evaluates each source independently. Smooth backgrounds and clean lighting compress efficiently; hair, fabric, foliage and camera noise need more data and may require smaller dimensions.",
    check: "Verify the downloaded byte size, format and pixel dimensions before submitting. If a portal rounds sizes differently, use a slightly lower custom target for extra margin.",
    faqs: [{ question: "Will the output be exactly 60KB?", answer: "The compressor chooses the closest practical result at or below 60KB, so it may be slightly smaller than the limit." }],
  },
  {
    slug: "80kb", label: "80KB", kb: 80, title: "Compress Image to 80KB Online Free",
    description: "Compress photos to 80KB free with no upload. Private JPG, PNG, WebP and HEIC compression runs in your browser.",
    intro: "Eighty kilobytes is a useful middle ground for application photos, ID-style portraits and website thumbnails. It is small enough for responsive uploads while allowing more detail than the very strict 20KB to 50KB range.",
    common: "An 80KB target works best after cropping and resizing to the destination’s required dimensions. Avoid spending the file budget on empty scenery or pixels that the receiving page will never display.",
    strategy: "The compressor first searches encoding quality, then carefully lowers dimensions only when required. That order protects useful resolution whenever the source complexity allows it.",
    check: "Compare the source and result at normal viewing size. Confirm important facial features, edges and text remain clear, and retain the untouched original separately.",
    faqs: [{ question: "Can I compress several images to 80KB?", answer: "Yes. Add multiple supported images and PixSqueeze applies the 80KB maximum to each file in the batch." }],
  },
  {
    slug: "90kb", label: "90KB", kb: 90, title: "Compress Image to 90KB Online Free",
    description: "Compress an image to 90KB online free and private. No-upload batch compression for JPG, PNG, WebP and HEIC files.",
    intro: "A 90KB preset is helpful when a portal sets a limit just below the familiar 100KB mark. Using the stated ceiling directly avoids accidental rejection from a result that is technically below 100KB but still above the form’s actual allowance.",
    common: "Choose 90KB for profile systems, education portals and web uploads that specify this exact maximum. For requirements expressed as a range, confirm the finished file also stays above any stated minimum.",
    strategy: "Begin with the cleanest available source. A previously compressed social-media copy contains artifacts that can make a second compression look worse than creating the 90KB version directly from the original.",
    check: "Review the download, then verify its true file properties rather than relying only on a rounded thumbnail label. Check the destination’s accepted extension and dimensions too.",
    faqs: [{ question: "Why use 90KB instead of 100KB?", answer: "A portal enforcing a 90KB ceiling can reject a file between 90KB and 100KB, so the target should match the stated rule." }],
  },
  {
    slug: "250kb", label: "250KB", kb: 250, title: "Compress Image to 250KB Online Free",
    description: "Compress an image to 250KB free with private no-upload processing. Reduce JPG, PNG, WebP and HEIC files in-browser.",
    intro: "Two hundred fifty kilobytes gives ordinary photos and scanned supporting images a comfortable amount of detail while remaining much lighter than a multi-megabyte camera original. It is a sensible limit for uploads that need legibility without unnecessary transfer weight.",
    common: "Use 250KB for document portals, listings, article images and email attachments that provide this ceiling. A large phone photo will usually benefit from sensible pixel dimensions as well as efficient encoding.",
    strategy: "PixSqueeze keeps the largest safe candidate it finds below 250KB. Detailed scenes may need stronger reduction than portraits or graphics with smooth backgrounds, even when their starting dimensions match.",
    check: "Inspect small text and important edges before submission. If the image is intended for print or close zooming, confirm that the destination’s resolution requirement is also satisfied.",
    faqs: [{ question: "Is 250KB enough for a clear photo?", answer: "It is usually enough for a clear medium-size screen image, though quality depends on pixel dimensions and visual complexity." }],
  },
  {
    slug: "400kb", label: "400KB", kb: 400, title: "Compress Image to 400KB Online Free",
    description: "Compress photos to 400KB online free. Private JPG, PNG, WebP and HEIC compression with no server upload or signup.",
    intro: "A 400KB target is generous enough for many detailed website, property, portfolio and supporting-document images while still reducing oversized phone and camera files substantially. It balances visible detail with quicker uploads and downloads.",
    common: "Choose 400KB when a platform explicitly sets that limit or when you want a consistent image budget for a batch. Resize sources that are far larger than their intended display area so visitors do not download unused pixels.",
    strategy: "At this target the compressor can often preserve substantial dimensions and rely mainly on efficient re-encoding. Already optimized WebP files may change less than high-resolution camera JPEGs.",
    check: "Preview the result in the context where it will appear. A large zoomable image may need more resolution than a card thumbnail even when both meet the same file-size limit.",
    faqs: [{ question: "Can I batch-compress website images to 400KB?", answer: "Yes. Each selected image is processed locally and receives its own result at or below the 400KB target when achievable." }],
  },
];

export const sizePages: SizePage[] = [...baseSizePages, ...additionalSizePages].sort((a, b) => a.kb - b.kb);

export function getSizePage(slug: string) { return sizePages.find((page) => page.slug === slug); }
